Repository Avdhesh-Varshney/AI-Code, pull requests merged in 2024-06, with the labels that each got.

#10 PR NO - #5 [Feature Added]--> ML - Algorithms under Regressions
  ML/Algorithms/Regressions/ElasticNetRegression/ElasticNetRegression.py
  ML/Algorithms/Regressions/ElasticNetRegression/README.md
  ML/Algorithms/Regressions/ElasticNetRegression/tests/test_ELasticNetRegression.py
Labels: bug 🐛, Requested Changes ⚙️

#14 Introduction to NLP Concepts and NLTK Setup Guide
  NLP/Algorithms/Installation_set-up_NLTK.ipynb
  NLP/Documentation/NLP_Introduction.md
Labels: Requested Changes ⚙️

#30 Fixed Issue #20 [Feature Request] Add loss functions for classification tasks
  ML/Algorithms/Losses/CrossEntropyLoss/cross_entropy_loss.py
  ML/Algorithms/Losses/HingeLoss/hinge_loss.py
  ML/Algorithms/Losses/KullbackLeiblerDivergenceLoss/kl_divergence.py
  ML/README.md
Labels: question❓

#31 added new loss functions
  ML/Algorithms/Losses/MeanAbsoluteError/MeanAbsoluteError.py
  ML/Algorithms/Losses/RootMeanSquaredError/RootMeanSquaredError.py
  ML/README.md
Labels: bug 🐛, Requested Changes ⚙️

#48 Nlp
  NLP/Algorithms/Installation_set-up_NLTK.ipynb
  NLP/Documentation/NLTK-Setup.md
  NLP/README.md
Labels: bug 🐛, Requested Changes ⚙️

#57 Addition of BoW algorithm Code
  NLP/Algorithms/BagOfWords/BagofWords.py
Labels: bug 🐛, Requested Changes ⚙️
