Repository Avdhesh-Varshney/AI-Code, pull requests merged in 2025-01, with the labels that each got.

#105 Add Sleep Prediction Model
  docs/ML/projects/sleep_quality_prediction.md
Labels: Warning: Follow Guidelines

#110 Name Entity Recognition Project using NLP Added
  docs/NLP/projects/name_entity_recognition.md
Labels: Status: Requested Changes, Warning: Follow Guidelines

#116 KMeans_Clustering.md
  docs/ML/algorithms/KMeans_Clustering.md
Labels: Status: Review Ongoing

#123 Heart Disease Detection using ML #108
  docs/ML/projects/Heart_Disease_Detection_Model.md
Labels: Status: Review Ongoing

#125 Add Colorization of Black and White Images using OpenCV
  docs/OpenCV/projects/black_and_white_image_colorizer.md
Labels: bug 🐛, Status: Requested Changes

#121 Next Word Prediction using LSTM
  docs/NLP/projects/next-word-pred.md
Labels: enhancement 🧑‍💻, Status: Review Ongoing

#147 added Poker Hand Prediction with 3 models
  docs/projects/machine-learning/poker-hand-prediction.md
Labels: Status: Review Ongoing

#151 Add/face detection model
  docs/projects/computer-vision/face-detection.md
  docs/projects/computer-vision/index.md
Labels: Status: Review Ongoing

#161 created template/updated
  ALGORITHM-README-TEMPLATE.md
  CONTRIBUTING.md
Labels: Status: Requested Changes

#158 Add/bicep reps
  docs/projects/computer-vision/counting-bicep-reps.md
  docs/projects/computer-vision/index.md
Labels: Status: Review Ongoing

#172 Add/brightness control
  docs/projects/computer-vision/brightness-control.md
  docs/projects/computer-vision/index.md
Labels: bug 🐛, Status: Requested Changes

#169 Add/logistic regression
  docs/algorithms/machine-learning/supervised/classifications/index.md
  docs/algorithms/machine-learning/supervised/regressions/Logistic_Regression.md
  docs/algorithms/machine-learning/supervised/regressions/index.md
  docs/algorithms/machine-learning/supervised/regressions/logistic-regression.md
Labels: Status: Review Ongoing

#173 Create text_summarization.md
  docs/projects/natural-language-processing/text_summarization.md
Labels: Status: Review Ongoing

#174 Add/contributors section
  README.md
Labels: Status: Review Ongoing
